// Mocks generated by Mockito 5.4.4 from annotations
// in xplor/test/features/on_boarding_test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dio/dio.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:shared_preferences/shared_preferences.dart' as _i4;
import 'package:xplor/const/local_storage/shared_preferences_helper.dart'
    as _i20;
import 'package:xplor/core/connection/network_info.dart' as _i19;
import 'package:xplor/features/on_boarding/data/data_sources/on_boarding_remote.dart'
    as _i16;
import 'package:xplor/features/on_boarding/data/models/e_auth_providers_model.dart'
    as _i17;
import 'package:xplor/features/on_boarding/domain/entities/categories_entity.dart'
    as _i14;
import 'package:xplor/features/on_boarding/domain/entities/domains_entity.dart'
    as _i13;
import 'package:xplor/features/on_boarding/domain/entities/e_auth_providers_entity.dart'
    as _i12;
import 'package:xplor/features/on_boarding/domain/entities/kyc_sse_response.dart'
    as _i15;
import 'package:xplor/features/on_boarding/domain/entities/ob_boarding_verify_otp_entity.dart'
    as _i9;
import 'package:xplor/features/on_boarding/domain/entities/on_boarding_assign_role_entity.dart'
    as _i10;
import 'package:xplor/features/on_boarding/domain/entities/on_boarding_send_otp_entity.dart'
    as _i7;
import 'package:xplor/features/on_boarding/domain/entities/on_boarding_user_role_entity.dart'
    as _i11;
import 'package:xplor/features/on_boarding/domain/entities/user_data_entity.dart'
    as _i2;
import 'package:xplor/features/on_boarding/domain/repository/on_boarding_repository.dart'
    as _i3;
import 'package:xplor/features/on_boarding/domain/usecase/on_boarding_usecase.dart'
    as _i18;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserDataEntity_0 extends _i1.SmartFake
    implements _i2.UserDataEntity {
  _FakeUserDataEntity_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOnBoardingRepository_1 extends _i1.SmartFake
    implements _i3.OnBoardingRepository {
  _FakeOnBoardingRepository_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSharedPreferences_2 extends _i1.SmartFake
    implements _i4.SharedPreferences {
  _FakeSharedPreferences_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBaseOptions_3 extends _i1.SmartFake implements _i5.BaseOptions {
  _FakeBaseOptions_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHttpClientAdapter_4 extends _i1.SmartFake
    implements _i5.HttpClientAdapter {
  _FakeHttpClientAdapter_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTransformer_5 extends _i1.SmartFake implements _i5.Transformer {
  _FakeTransformer_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInterceptors_6 extends _i1.SmartFake implements _i5.Interceptors {
  _FakeInterceptors_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_7<T1> extends _i1.SmartFake implements _i5.Response<T1> {
  _FakeResponse_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [OnBoardingRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockOnBoardingRepository extends _i1.Mock
    implements _i3.OnBoardingRepository {
  MockOnBoardingRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<String> sendOtpOnBoarding(_i7.OnBoardingSendOtpEntity? entity) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendOtpOnBoarding,
          [entity],
        ),
        returnValue: _i6.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #sendOtpOnBoarding,
            [entity],
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<void> verifyOtpOnBoarding(_i9.OnBoardingVerifyOtpEntity? entity) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyOtpOnBoarding,
          [entity],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> assignRoleOnBoarding(
          _i10.OnBoardingAssignRoleEntity? entity) =>
      (super.noSuchMethod(
        Invocation.method(
          #assignRoleOnBoarding,
          [entity],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> updateUserKycOnBoarding() => (super.noSuchMethod(
        Invocation.method(
          #updateUserKycOnBoarding,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> createMpin(String? pin) => (super.noSuchMethod(
        Invocation.method(
          #createMpin,
          [pin],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<List<_i11.OnBoardingUserRoleEntity>> getUserRolesOnBoarding() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserRolesOnBoarding,
          [],
        ),
        returnValue: _i6.Future<List<_i11.OnBoardingUserRoleEntity>>.value(
            <_i11.OnBoardingUserRoleEntity>[]),
      ) as _i6.Future<List<_i11.OnBoardingUserRoleEntity>>);

  @override
  _i6.Future<_i12.EAuthProviderEntity?> getEAuthProviders() =>
      (super.noSuchMethod(
        Invocation.method(
          #getEAuthProviders,
          [],
        ),
        returnValue: _i6.Future<_i12.EAuthProviderEntity?>.value(),
      ) as _i6.Future<_i12.EAuthProviderEntity?>);

  @override
  _i6.Future<void> getUserJourney() => (super.noSuchMethod(
        Invocation.method(
          #getUserJourney,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> getAssignedRoleUserData() => (super.noSuchMethod(
        Invocation.method(
          #getAssignedRoleUserData,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> updateDevicePreference(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDevicePreference,
          [data],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<List<_i13.DomainData>> getDomainsList() => (super.noSuchMethod(
        Invocation.method(
          #getDomainsList,
          [],
        ),
        returnValue:
            _i6.Future<List<_i13.DomainData>>.value(<_i13.DomainData>[]),
      ) as _i6.Future<List<_i13.DomainData>>);

  @override
  _i6.Future<bool> getDeviceInfoApi(String? domains) => (super.noSuchMethod(
        Invocation.method(
          #getDeviceInfoApi,
          [domains],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<List<_i14.CategoryEntity>> getCategories() => (super.noSuchMethod(
        Invocation.method(
          #getCategories,
          [],
        ),
        returnValue: _i6.Future<List<_i14.CategoryEntity>>.value(
            <_i14.CategoryEntity>[]),
      ) as _i6.Future<List<_i14.CategoryEntity>>);

  @override
  _i6.Future<void> onCategoriesSave(List<String>? categories) =>
      (super.noSuchMethod(
        Invocation.method(
          #onCategoriesSave,
          [categories],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i2.UserDataEntity> getUserData() => (super.noSuchMethod(
        Invocation.method(
          #getUserData,
          [],
        ),
        returnValue: _i6.Future<_i2.UserDataEntity>.value(_FakeUserDataEntity_0(
          this,
          Invocation.method(
            #getUserData,
            [],
          ),
        )),
      ) as _i6.Future<_i2.UserDataEntity>);

  @override
  _i6.Stream<_i15.KycSseResponse> getKycStatusResponse(Duration? timeout) =>
      (super.noSuchMethod(
        Invocation.method(
          #getKycStatusResponse,
          [timeout],
        ),
        returnValue: _i6.Stream<_i15.KycSseResponse>.empty(),
      ) as _i6.Stream<_i15.KycSseResponse>);
}

/// A class which mocks [OnBoardingApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOnBoardingApiService extends _i1.Mock
    implements _i16.OnBoardingApiService {
  MockOnBoardingApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<String> sendOtpOnBoarding(_i7.OnBoardingSendOtpEntity? entity) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendOtpOnBoarding,
          [entity],
        ),
        returnValue: _i6.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #sendOtpOnBoarding,
            [entity],
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<void> verifyOtpOnBoarding(_i9.OnBoardingVerifyOtpEntity? entity) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyOtpOnBoarding,
          [entity],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> getUserJourney() => (super.noSuchMethod(
        Invocation.method(
          #getUserJourney,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> assignRoleOnBoarding(
          _i10.OnBoardingAssignRoleEntity? entity) =>
      (super.noSuchMethod(
        Invocation.method(
          #assignRoleOnBoarding,
          [entity],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<List<_i11.OnBoardingUserRoleEntity>> getUserRolesOnBoarding() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserRolesOnBoarding,
          [],
        ),
        returnValue: _i6.Future<List<_i11.OnBoardingUserRoleEntity>>.value(
            <_i11.OnBoardingUserRoleEntity>[]),
      ) as _i6.Future<List<_i11.OnBoardingUserRoleEntity>>);

  @override
  _i6.Future<bool> updateUserKycOnBoarding() => (super.noSuchMethod(
        Invocation.method(
          #updateUserKycOnBoarding,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> createMpin(String? pin) => (super.noSuchMethod(
        Invocation.method(
          #createMpin,
          [pin],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<_i17.EAuthProviderModel?> getEAuthProviders() =>
      (super.noSuchMethod(
        Invocation.method(
          #getEAuthProviders,
          [],
        ),
        returnValue: _i6.Future<_i17.EAuthProviderModel?>.value(),
      ) as _i6.Future<_i17.EAuthProviderModel?>);

  @override
  _i6.Future<void> getAssignedRoleUserData() => (super.noSuchMethod(
        Invocation.method(
          #getAssignedRoleUserData,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> updateDevicePreference(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDevicePreference,
          [data],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<List<_i13.DomainData>> getDomainsList() => (super.noSuchMethod(
        Invocation.method(
          #getDomainsList,
          [],
        ),
        returnValue:
            _i6.Future<List<_i13.DomainData>>.value(<_i13.DomainData>[]),
      ) as _i6.Future<List<_i13.DomainData>>);

  @override
  _i6.Future<bool> getDeviceInfo(String? deviceId) => (super.noSuchMethod(
        Invocation.method(
          #getDeviceInfo,
          [deviceId],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<List<_i14.CategoryEntity>> getCategories() => (super.noSuchMethod(
        Invocation.method(
          #getCategories,
          [],
        ),
        returnValue: _i6.Future<List<_i14.CategoryEntity>>.value(
            <_i14.CategoryEntity>[]),
      ) as _i6.Future<List<_i14.CategoryEntity>>);

  @override
  _i6.Future<void> onCategoriesSave(List<String>? categories) =>
      (super.noSuchMethod(
        Invocation.method(
          #onCategoriesSave,
          [categories],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i2.UserDataEntity> getUserData() => (super.noSuchMethod(
        Invocation.method(
          #getUserData,
          [],
        ),
        returnValue: _i6.Future<_i2.UserDataEntity>.value(_FakeUserDataEntity_0(
          this,
          Invocation.method(
            #getUserData,
            [],
          ),
        )),
      ) as _i6.Future<_i2.UserDataEntity>);

  @override
  _i6.Stream<_i15.KycSseResponse> getKycSuccessStatus(Duration? timeout) =>
      (super.noSuchMethod(
        Invocation.method(
          #getKycSuccessStatus,
          [timeout],
        ),
        returnValue: _i6.Stream<_i15.KycSseResponse>.empty(),
      ) as _i6.Stream<_i15.KycSseResponse>);
}

/// A class which mocks [OnBoardingUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockOnBoardingUseCase extends _i1.Mock implements _i18.OnBoardingUseCase {
  MockOnBoardingUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.OnBoardingRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeOnBoardingRepository_1(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i3.OnBoardingRepository);

  @override
  set repository(_i3.OnBoardingRepository? _repository) => super.noSuchMethod(
        Invocation.setter(
          #repository,
          _repository,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<String> call({_i7.OnBoardingSendOtpEntity? params}) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {#params: params},
        ),
        returnValue: _i6.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #call,
            [],
            {#params: params},
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<void> verifyOtpOnBoarding(_i9.OnBoardingVerifyOtpEntity? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyOtpOnBoarding,
          [params],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> assignRoleOnBoarding(
          _i10.OnBoardingAssignRoleEntity? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #assignRoleOnBoarding,
          [params],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> updateUserKycOnBoarding() => (super.noSuchMethod(
        Invocation.method(
          #updateUserKycOnBoarding,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<_i12.EAuthProviderEntity?> getEAuthProviders() =>
      (super.noSuchMethod(
        Invocation.method(
          #getEAuthProviders,
          [],
        ),
        returnValue: _i6.Future<_i12.EAuthProviderEntity?>.value(),
      ) as _i6.Future<_i12.EAuthProviderEntity?>);

  @override
  _i6.Future<List<_i11.OnBoardingUserRoleEntity>> getUserRolesOnBoarding() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserRolesOnBoarding,
          [],
        ),
        returnValue: _i6.Future<List<_i11.OnBoardingUserRoleEntity>>.value(
            <_i11.OnBoardingUserRoleEntity>[]),
      ) as _i6.Future<List<_i11.OnBoardingUserRoleEntity>>);

  @override
  _i6.Future<void> getUserJourney() => (super.noSuchMethod(
        Invocation.method(
          #getUserJourney,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> createMpin(String? pin) => (super.noSuchMethod(
        Invocation.method(
          #createMpin,
          [pin],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<void> getAssignedRoleUserData() => (super.noSuchMethod(
        Invocation.method(
          #getAssignedRoleUserData,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> updateDevicePreference(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDevicePreference,
          [data],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<List<_i13.DomainData>> getDomains() => (super.noSuchMethod(
        Invocation.method(
          #getDomains,
          [],
        ),
        returnValue:
            _i6.Future<List<_i13.DomainData>>.value(<_i13.DomainData>[]),
      ) as _i6.Future<List<_i13.DomainData>>);

  @override
  _i6.Future<bool> getDeviceIdEvent(String? deviceId) => (super.noSuchMethod(
        Invocation.method(
          #getDeviceIdEvent,
          [deviceId],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<List<_i14.CategoryEntity>> getCategories() => (super.noSuchMethod(
        Invocation.method(
          #getCategories,
          [],
        ),
        returnValue: _i6.Future<List<_i14.CategoryEntity>>.value(
            <_i14.CategoryEntity>[]),
      ) as _i6.Future<List<_i14.CategoryEntity>>);

  @override
  _i6.Future<_i2.UserDataEntity> getUserData() => (super.noSuchMethod(
        Invocation.method(
          #getUserData,
          [],
        ),
        returnValue: _i6.Future<_i2.UserDataEntity>.value(_FakeUserDataEntity_0(
          this,
          Invocation.method(
            #getUserData,
            [],
          ),
        )),
      ) as _i6.Future<_i2.UserDataEntity>);

  @override
  _i6.Stream<_i15.KycSseResponse> getKycSuccessStatusResponse(
          Duration? timeout) =>
      (super.noSuchMethod(
        Invocation.method(
          #getKycSuccessStatusResponse,
          [timeout],
        ),
        returnValue: _i6.Stream<_i15.KycSseResponse>.empty(),
      ) as _i6.Stream<_i15.KycSseResponse>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i19.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [SharedPreferencesHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferencesHelper extends _i1.Mock
    implements _i20.SharedPreferencesHelper {
  MockSharedPreferencesHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.SharedPreferences get sharedPreferences => (super.noSuchMethod(
        Invocation.getter(#sharedPreferences),
        returnValue: _FakeSharedPreferences_2(
          this,
          Invocation.getter(#sharedPreferences),
        ),
      ) as _i4.SharedPreferences);

  @override
  set sharedPreferences(_i4.SharedPreferences? _sharedPreferences) =>
      super.noSuchMethod(
        Invocation.setter(
          #sharedPreferences,
          _sharedPreferences,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<dynamic> init({_i4.SharedPreferences? preferences}) =>
      (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
          {#preferences: preferences},
        ),
        returnValue: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);

  @override
  String getString(
    String? key, {
    String? defaultValue = r'NA',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getString,
          [key],
          {#defaultValue: defaultValue},
        ),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #getString,
            [key],
            {#defaultValue: defaultValue},
          ),
        ),
      ) as String);

  @override
  double getDouble(
    String? key, {
    double? defaultValue = 0.0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDouble,
          [key],
          {#defaultValue: defaultValue},
        ),
        returnValue: 0.0,
      ) as double);

  @override
  bool getBoolean(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getBoolean,
          [key],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i6.Future<bool> setString(
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setString,
          [
            key,
            value,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> setDouble(
    String? key,
    double? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setDouble,
          [
            key,
            value,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> setBoolean(
    String? key,
    bool? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setBoolean,
          [
            key,
            value,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  List<String> getStringList(
    String? key, {
    List<String>? defaultValue = const [],
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStringList,
          [key],
          {#defaultValue: defaultValue},
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  _i6.Future<bool> setStringList(
    String? key,
    List<String>? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setStringList,
          [
            key,
            value,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);
}

/// A class which mocks [Dio].
///
/// See the documentation for Mockito's code generation for more information.
class MockDio extends _i1.Mock implements _i5.Dio {
  MockDio() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.BaseOptions get options => (super.noSuchMethod(
        Invocation.getter(#options),
        returnValue: _FakeBaseOptions_3(
          this,
          Invocation.getter(#options),
        ),
      ) as _i5.BaseOptions);

  @override
  set options(_i5.BaseOptions? _options) => super.noSuchMethod(
        Invocation.setter(
          #options,
          _options,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.HttpClientAdapter get httpClientAdapter => (super.noSuchMethod(
        Invocation.getter(#httpClientAdapter),
        returnValue: _FakeHttpClientAdapter_4(
          this,
          Invocation.getter(#httpClientAdapter),
        ),
      ) as _i5.HttpClientAdapter);

  @override
  set httpClientAdapter(_i5.HttpClientAdapter? _httpClientAdapter) =>
      super.noSuchMethod(
        Invocation.setter(
          #httpClientAdapter,
          _httpClientAdapter,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Transformer get transformer => (super.noSuchMethod(
        Invocation.getter(#transformer),
        returnValue: _FakeTransformer_5(
          this,
          Invocation.getter(#transformer),
        ),
      ) as _i5.Transformer);

  @override
  set transformer(_i5.Transformer? _transformer) => super.noSuchMethod(
        Invocation.setter(
          #transformer,
          _transformer,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Interceptors get interceptors => (super.noSuchMethod(
        Invocation.getter(#interceptors),
        returnValue: _FakeInterceptors_6(
          this,
          Invocation.getter(#interceptors),
        ),
      ) as _i5.Interceptors);

  @override
  void close({bool? force = false}) => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
          {#force: force},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<_i5.Response<T>> head<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i5.Options? options,
    _i5.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i6.Future<_i5.Response<T>>.value(_FakeResponse_7<T>(
          this,
          Invocation.method(
            #head,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i6.Future<_i5.Response<T>>);

  @override
  _i6.Future<_i5.Response<T>> headUri<T>(
    Uri? uri, {
    Object? data,
    _i5.Options? options,
    _i5.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #headUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i6.Future<_i5.Response<T>>.value(_FakeResponse_7<T>(
          this,
          Invocation.method(
            #headUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i6.Future<_i5.Response<T>>);

  @override
  _i6.Future<_i5.Response<T>> get<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i5.Options? options,
    _i5.CancelToken? cancelToken,
    _i5.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i6.Future<_i5.Response<T>>.value(_FakeResponse_7<T>(
          this,
          Invocation.method(
            #get,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i6.Future<_i5.Response<T>>);

  @override
  _i6.Future<_i5.Response<T>> getUri<T>(
    Uri? uri, {
    Object? data,
    _i5.Options? options,
    _i5.CancelToken? cancelToken,
    _i5.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i6.Future<_i5.Response<T>>.value(_FakeResponse_7<T>(
          this,
          Invocation.method(
            #getUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i6.Future<_i5.Response<T>>);

  @override
  _i6.Future<_i5.Response<T>> post<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i5.Options? options,
    _i5.CancelToken? cancelToken,
    _i5.ProgressCallback? onSendProgress,
    _i5.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i6.Future<_i5.Response<T>>.value(_FakeResponse_7<T>(
          this,
          Invocation.method(
            #post,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i6.Future<_i5.Response<T>>);

  @override
  _i6.Future<_i5.Response<T>> postUri<T>(
    Uri? uri, {
    Object? data,
    _i5.Options? options,
    _i5.CancelToken? cancelToken,
    _i5.ProgressCallback? onSendProgress,
    _i5.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i6.Future<_i5.Response<T>>.value(_FakeResponse_7<T>(
          this,
          Invocation.method(
            #postUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i6.Future<_i5.Response<T>>);

  @override
  _i6.Future<_i5.Response<T>> put<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i5.Options? options,
    _i5.CancelToken? cancelToken,
    _i5.ProgressCallback? onSendProgress,
    _i5.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i6.Future<_i5.Response<T>>.value(_FakeResponse_7<T>(
          this,
          Invocation.method(
            #put,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i6.Future<_i5.Response<T>>);

  @override
  _i6.Future<_i5.Response<T>> putUri<T>(
    Uri? uri, {
    Object? data,
    _i5.Options? options,
    _i5.CancelToken? cancelToken,
    _i5.ProgressCallback? onSendProgress,
    _i5.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #putUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i6.Future<_i5.Response<T>>.value(_FakeResponse_7<T>(
          this,
          Invocation.method(
            #putUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i6.Future<_i5.Response<T>>);

  @override
  _i6.Future<_i5.Response<T>> patch<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i5.Options? options,
    _i5.CancelToken? cancelToken,
    _i5.ProgressCallback? onSendProgress,
    _i5.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i6.Future<_i5.Response<T>>.value(_FakeResponse_7<T>(
          this,
          Invocation.method(
            #patch,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i6.Future<_i5.Response<T>>);

  @override
  _i6.Future<_i5.Response<T>> patchUri<T>(
    Uri? uri, {
    Object? data,
    _i5.Options? options,
    _i5.CancelToken? cancelToken,
    _i5.ProgressCallback? onSendProgress,
    _i5.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patchUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i6.Future<_i5.Response<T>>.value(_FakeResponse_7<T>(
          this,
          Invocation.method(
            #patchUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i6.Future<_i5.Response<T>>);

  @override
  _i6.Future<_i5.Response<T>> delete<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i5.Options? options,
    _i5.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i6.Future<_i5.Response<T>>.value(_FakeResponse_7<T>(
          this,
          Invocation.method(
            #delete,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i6.Future<_i5.Response<T>>);

  @override
  _i6.Future<_i5.Response<T>> deleteUri<T>(
    Uri? uri, {
    Object? data,
    _i5.Options? options,
    _i5.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i6.Future<_i5.Response<T>>.value(_FakeResponse_7<T>(
          this,
          Invocation.method(
            #deleteUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i6.Future<_i5.Response<T>>);

  @override
  _i6.Future<_i5.Response<dynamic>> download(
    String? urlPath,
    dynamic savePath, {
    _i5.ProgressCallback? onReceiveProgress,
    Map<String, dynamic>? queryParameters,
    _i5.CancelToken? cancelToken,
    bool? deleteOnError = true,
    String? lengthHeader = r'content-length',
    Object? data,
    _i5.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #download,
          [
            urlPath,
            savePath,
          ],
          {
            #onReceiveProgress: onReceiveProgress,
            #queryParameters: queryParameters,
            #cancelToken: cancelToken,
            #deleteOnError: deleteOnError,
            #lengthHeader: lengthHeader,
            #data: data,
            #options: options,
          },
        ),
        returnValue:
            _i6.Future<_i5.Response<dynamic>>.value(_FakeResponse_7<dynamic>(
          this,
          Invocation.method(
            #download,
            [
              urlPath,
              savePath,
            ],
            {
              #onReceiveProgress: onReceiveProgress,
              #queryParameters: queryParameters,
              #cancelToken: cancelToken,
              #deleteOnError: deleteOnError,
              #lengthHeader: lengthHeader,
              #data: data,
              #options: options,
            },
          ),
        )),
      ) as _i6.Future<_i5.Response<dynamic>>);

  @override
  _i6.Future<_i5.Response<dynamic>> downloadUri(
    Uri? uri,
    dynamic savePath, {
    _i5.ProgressCallback? onReceiveProgress,
    _i5.CancelToken? cancelToken,
    bool? deleteOnError = true,
    String? lengthHeader = r'content-length',
    Object? data,
    _i5.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadUri,
          [
            uri,
            savePath,
          ],
          {
            #onReceiveProgress: onReceiveProgress,
            #cancelToken: cancelToken,
            #deleteOnError: deleteOnError,
            #lengthHeader: lengthHeader,
            #data: data,
            #options: options,
          },
        ),
        returnValue:
            _i6.Future<_i5.Response<dynamic>>.value(_FakeResponse_7<dynamic>(
          this,
          Invocation.method(
            #downloadUri,
            [
              uri,
              savePath,
            ],
            {
              #onReceiveProgress: onReceiveProgress,
              #cancelToken: cancelToken,
              #deleteOnError: deleteOnError,
              #lengthHeader: lengthHeader,
              #data: data,
              #options: options,
            },
          ),
        )),
      ) as _i6.Future<_i5.Response<dynamic>>);

  @override
  _i6.Future<_i5.Response<T>> request<T>(
    String? url, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i5.CancelToken? cancelToken,
    _i5.Options? options,
    _i5.ProgressCallback? onSendProgress,
    _i5.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #request,
          [url],
          {
            #data: data,
            #queryParameters: queryParameters,
            #cancelToken: cancelToken,
            #options: options,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i6.Future<_i5.Response<T>>.value(_FakeResponse_7<T>(
          this,
          Invocation.method(
            #request,
            [url],
            {
              #data: data,
              #queryParameters: queryParameters,
              #cancelToken: cancelToken,
              #options: options,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i6.Future<_i5.Response<T>>);

  @override
  _i6.Future<_i5.Response<T>> requestUri<T>(
    Uri? uri, {
    Object? data,
    _i5.CancelToken? cancelToken,
    _i5.Options? options,
    _i5.ProgressCallback? onSendProgress,
    _i5.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestUri,
          [uri],
          {
            #data: data,
            #cancelToken: cancelToken,
            #options: options,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i6.Future<_i5.Response<T>>.value(_FakeResponse_7<T>(
          this,
          Invocation.method(
            #requestUri,
            [uri],
            {
              #data: data,
              #cancelToken: cancelToken,
              #options: options,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i6.Future<_i5.Response<T>>);

  @override
  _i6.Future<_i5.Response<T>> fetch<T>(_i5.RequestOptions? requestOptions) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetch,
          [requestOptions],
        ),
        returnValue: _i6.Future<_i5.Response<T>>.value(_FakeResponse_7<T>(
          this,
          Invocation.method(
            #fetch,
            [requestOptions],
          ),
        )),
      ) as _i6.Future<_i5.Response<T>>);
}
